# Generated by Django 4.1.6 on 2023-02-05 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=100)),
                ("department_id", models.CharField(max_length=100)),
                (
                    "department_school",
                    models.CharField(
                        choices=[
                            (
                                "SCOPE",
                                "School of Computer Science and Engineering-SCOPE",
                            ),
                            ("SAS", "School of Advanced Sciences-SAS"),
                            ("SSL", "School of Social Sciences and Languages-SSL"),
                            ("SENSE", "School of Electronics Engineering-SENSE"),
                            ("SELECT", "School of Electrical Engineering-SELECT"),
                            ("SMEC", "School of Mechanical Engineering-SMEC"),
                            ("SCE", "School of Civil Engineering-SCE"),
                            ("VITBS", "VIT Business School-VITBS"),
                            ("VITSOL", "VIT School of Law-VITSOL"),
                            ("VFIT", "VIT Fashion Institute of Technology-VFIT"),
                            ("Other Organization", "Other Organization"),
                            ("Unauthorized", "Unauthorized"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecruitmentDrive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recruitment_title", models.CharField(max_length=200)),
                ("start_date_time", models.DateTimeField()),
                ("end_date_time", models.DateTimeField()),
                ("recruitment_term", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("Open", "Open"), ("Closed", "Closed")], max_length=100
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Design and Content", "Design and Content"),
                            ("UI/UX", "UI/UX"),
                            ("Management", "Management"),
                            ("Finance", "Finance"),
                            ("Sponsership", "Sponsership"),
                            ("Cybersecurity", "Cybersecurity"),
                            ("Competitive Programming", "Competitive Programming"),
                            ("Development - Web", "Development - Web"),
                            ("Development - App", "Development - App"),
                            ("All", "All"),
                        ],
                        default="All",
                        max_length=100,
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Applicant", "Applicant"),
                            ("Head/Lead", "Head/Lead"),
                            ("President", "President"),
                            ("Vice President", "Vice President"),
                            ("Unauthorized", "Unauthorized"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("admitted_year", models.CharField(max_length=500, null=True)),
                ("slug", models.SlugField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department_preferences",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Design and Content", "Design and Content"),
                            ("UI/UX", "UI/UX"),
                            ("Management", "Management"),
                            ("Finance", "Finance"),
                            ("Sponsership", "Sponsership"),
                            ("Cybersecurity", "Cybersecurity"),
                            ("Competitive Programming", "Competitive Programming"),
                            ("Development - Web", "Development - Web"),
                            ("Development - App", "Development - App"),
                        ],
                        max_length=100,
                    ),
                ),
                ("linkedin_url", models.URLField()),
                ("instagram_id", models.CharField(max_length=100)),
                ("lookup_skills", models.CharField(max_length=400)),
                ("question_one", models.TextField(max_length=400)),
                ("question_two", models.TextField(blank=True, max_length=400)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Application under Review", "Application under Review"),
                            ("Shortlisted for Interview", "Shortlisted for Interview"),
                            ("Accepted", "Accepted"),
                            ("Mentorship", "Mentorship"),
                            ("Rejected", "Rejected"),
                        ],
                        max_length=100,
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                ("date_of_application", models.DateTimeField(auto_now_add=True)),
                (
                    "recruitment_drive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.recruitmentdrive",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
