# Generated by Django 4.1.6 on 2023-02-04 16:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="deparment_preferences",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Design and Content", "Design and Content"),
                    ("UI/UX", "UI/UX"),
                    ("Management", "Management"),
                    ("Finance", "Finance"),
                    ("Sponsership", "Sponsership"),
                    ("Cybersecurity", "Cybersecurity"),
                    ("Competitive Programming", "Competitive Programming"),
                    ("Development - Web", "Development - Web"),
                    ("Development - App", "Development - App"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Application under Process", "Application under Process"),
                    ("Shortlisted for Interview", "Shortlisted for Interview"),
                    ("Accepted", "Accepted"),
                    ("Mentorship", "Mentorship"),
                    ("Rejected", "Rejected"),
                ],
                max_length=100,
            ),
        ),
    ]
