# Generated by Django 4.1.6 on 2023-02-08 03:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="department_preferences",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Design and Content", "Design and Content"),
                    ("UI/UX", "UI/UX"),
                    ("Management", "Management"),
                    ("Finance", "Finance"),
                    ("Sponsership", "Sponsership"),
                    ("Cybersecurity", "Cybersecurity"),
                    ("Competitive Programming", "Competitive Programming"),
                    ("Development - Web", "Development - Web"),
                    ("Development - App", "Development - App"),
                    ("AI/ML", "AI/ML"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="recruitmentdrive",
            name="department",
            field=models.CharField(
                choices=[
                    ("Design and Content", "Design and Content"),
                    ("UI/UX", "UI/UX"),
                    ("Management", "Management"),
                    ("Finance", "Finance"),
                    ("Sponsership", "Sponsership"),
                    ("Cybersecurity", "Cybersecurity"),
                    ("Competitive Programming", "Competitive Programming"),
                    ("Development - Web", "Development - Web"),
                    ("Development - App", "Development - App"),
                    ("AI/ML", "AI/ML"),
                    ("All", "All"),
                ],
                default="All",
                max_length=100,
            ),
        ),
    ]
