# Generated by Django 4.1.6 on 2023-02-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Applicant", "Applicant"),
                    ("Head/Lead", "Head/Lead"),
                    ("President", "President"),
                    ("Vice President", "Vice President"),
                    ("Secretary", "Secretary"),
                    ("Joint General Secretary", "Joint General Security"),
                    ("Unauthorized", "Unauthorized"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
