# Generated by Django 4.1.6 on 2023-02-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0002_rename_deparment_preferences_application_department_preferences",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Application under Review", "Application under Review"),
                    ("Shortlisted for Interview", "Shortlisted for Interview"),
                    ("Accepted", "Accepted"),
                    ("Mentorship", "Mentorship"),
                    ("Rejected", "Rejected"),
                ],
                max_length=100,
            ),
        ),
    ]
