# Generated by Django 4.1.6 on 2023-02-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_application_deparment_preferences_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recruitmentdrive",
            old_name="end_data_time",
            new_name="end_date_time",
        ),
    ]
