# Generated by Django 4.1.6 on 2023-02-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_application_date_of_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="question_one",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="application",
            name="question_two",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
