# Generated by Django 4.1.7 on 2023-03-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_application_department_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Application under Review', 'Application under Review'), ('Shortlisted for Contest', 'Shortlisted for Contest'), ('Shortlisted for Interview', 'Shortlisted for Interview'), ('Accepted', 'Accepted'), ('Mentorship', 'Mentorship'), ('Rejected', 'Rejected')], max_length=100),
        ),
    ]
