# Generated by Django 4.1.7 on 2023-03-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_alter_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="accepted_department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Design and Content", "Design and Content"),
                    ("UI/UX", "UI/UX"),
                    ("Management", "Management"),
                    ("Sponsorship", "Sponsorship"),
                    ("Cybersecurity", "Cybersecurity"),
                    ("Competitive Programming", "Competitive Programming"),
                    ("Development - Web", "Development - Web"),
                    ("Development - App", "Development - App"),
                    ("AI/ML", "AI/ML"),
                    ("Video Editing and Photography", "Video Editing and Photography"),
                ],
                max_length=500,
                null=True,
            ),
        ),
    ]
